[slurm_controller]
spark-38fc ansible_host=192.168.1.82 ansible_user=chris ansible_python_interpreter=/usr/bin/python3.12

[slurm_compute]
spark-1ac4 ansible_host=192.168.1.229 ansible_user=chris ansible_python_interpreter=/usr/bin/python3.12

[dgx:children]
slurm_controller
slurm_compute