apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
      "periodicUpdateInterval": 300,
      "configList": [
        {
          "resourceName": "rdma_shared_device_a",
          "rdmaHcaMax": 63,
          "selectors": { "ifNames": ["enp1s0f1np1"] }
        },
        {
          "resourceName": "rdma_shared_device_b",
          "rdmaHcaMax": 63,
          "selectors": { "ifNames": ["enP2p1s0f1np1"] }
        }
      ]
    }
